# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170410_1309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['updated_at', 'created_at']},
        ),
    ]
